profile = "prof" # AWS profile
cluster = "prof-ite" # name of ECS cluster
task_definition = "prof-ite-app" # name of the task definition
container_name = "app" # name of the container

log_group = "ecs-tool"

[deploy]
services = ["app", "tasks"]

[ssh]
shell = "bash"
service = "app"
instance_user = "ec2-user"
