version: 2
jobs:
  build:
    docker:
      - image: golang:1.12-alpine
        environment:
          - CGO_ENABLED: 0

    working_directory: /app

    steps:
      - run:
          name: update and install tool dependencies
          command: |-
              apk update && apk add --no-cache git openssh-client

      - checkout

      - run:
          name: install go deps
          command: go mod download

      - run:
          name: test
          command: go test ./... -v

      - run:
          name: build
          command: go build

      - run:
          name: print help
          command: ./ecs-tool -h
